In [2]:

import xarray as xr
import pandas as pd
import os
from datetime import datetime
import geopandas as gpd

In [42]:
gdf = gpd.read_file('/home/exouser/Documents/cat-485547/config/cat-485547_subset.gpkg',layer="divides")
area = gdf.loc[gdf['divide_id'] == 'cat-' + str(485547) , 'areasqkm'].values[0]
area

11.945248978498336

AttributeError: 'GeoDataFrame' object has no attribute 'data_vars'

In [20]:
df_cat = pd.read_csv('/home/exouser/Documents/cat-485547/outputs/ngen/cat-485547.csv')
df_cat

,Time Step,Time,RAIN_RATE,GIUH_RUNOFF,INFILTRATION_EXCESS,DIRECT_RUNOFF,NASH_LATERAL_RUNOFF,DEEP_GW_TO_CHANNEL_FLUX,SOIL_TO_GW_FLUX,Q_OUT,POTENTIAL_ET,ACTUAL_ET,GW_STORAGE,SOIL_STORAGE,SOIL_STORAGE_CHANGE,SURF_RUNOFF_SCHEME,NWM_PONDED_DEPTH
0,0,2010-01-01 00:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000809,0.0,0.000809,0.000179,0.000000,0.007533,0.045028,0.000000,1.0,0.000000
1,1,2010-01-01 01:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000725,0.0,0.000725,0.000133,0.000000,0.006807,0.045028,0.000000,1.0,0.000000
2,2,2010-01-01 02:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000651,0.0,0.000651,0.000103,0.000000,0.006156,0.045028,0.000000,1.0,0.000000
3,3,2010-01-01 03:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000585,0.0,0.000585,0.000088,0.000000,0.005571,0.045028,0.000000,1.0,0.000000
4,4,2010-01-01 04:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000527,0.0,0.000527,0.000078,0.000000,0.005044,0.045028,0.000000,1.0,0.000000
5,5,2010-01-01 05:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000475,0.0,0.000475,0.000071,0.000000,0.004570,0.045028,0.000000,1.0,0.000000
6,6,2010-01-01 06:00:00,0.000058,0.000000,0.000000,0.000000,0.0,0.000428,0.0,0.000428,0.000064,0.000058,0.004141,0.045028,0.000000,1.0,0.000000
7,7,2010-01-01 07:00:00,0.001453,0.000011,0.000019,0.000011,0.0,0.000387,0.0,0.000397,0.000057,0.000057,0.003755,0.046405,0.001376,1.0,0.000009
8,8,2010-01-01 08:00:00,0.000194,0.000005,0.000000,0.000005,0.0,0.000349,0.0,0.000354,0.000055,0.000055,0.003406,0.046544,0.000139,1.0,0.000004
9,9,2010-01-01 09:00:00,0.001020,0.000009,0.000009,0.000009,0.0,0.000316,0.0,0.000325,0.000053,0.000053,0.003090,0.047502,0.000958,1.0,0.000004
10,10,2010-01-01 10:00:00,0.000199,0.000003,0.000000,0.000003,0.0,0.000286,0.0,0.000288,0.000056,0.000056,0.002804,0.047644,0.000142,1.0,0.000002
11,11,2010-01-01 11:00:00,0.000393,0.000003,0.000001,0.000003,0.0,0.000259,0.0,0.000261,0.000060,0.000060,0.002546,0.047976,0.000332,1.0,0.000001
12,12,2010-01-01 12:00:00,0.000192,0.000000,0.000000,0.000000,0.0,0.000234,0.0,0.000235,0.000061,0.000061,0.002311,0.048107,0.000131,1.0,0.000000
13,13,2010-01-01 13:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000212,0.0,0.000212,0.000065,0.000000,0.002099,0.048107,0.000000,1.0,0.000000
14,14,2010-01-01 14:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000192,0.0,0.000192,0.000083,0.000000,0.001907,0.048107,0.000000,1.0,0.000000
15,15,2010-01-01 15:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000174,0.0,0.000174,0.000108,0.000000,0.001732,0.048107,0.000000,1.0,0.000000
16,16,2010-01-01 16:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000158,0.0,0.000158,0.000132,0.000000,0.001574,0.048107,0.000000,1.0,0.000000
17,17,2010-01-01 17:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000144,0.0,0.000144,0.000156,0.000000,0.001431,0.048107,0.000000,1.0,0.000000
18,18,2010-01-01 18:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000130,0.0,0.000130,0.000172,0.000000,0.001300,0.048107,0.000000,1.0,0.000000
19,19,2010-01-01 19:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000118,0.0,0.000118,0.000172,0.000000,0.001182,0.048107,0.000000,1.0,0.000000
20,20,2010-01-01 20:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000107,0.0,0.000107,0.000166,0.000000,0.001075,0.048107,0.000000,1.0,0.000000
21,21,2010-01-01 21:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000098,0.0,0.000098,0.000132,0.000000,0.000977,0.048107,0.000000,1.0,0.000000
22,22,2010-01-01 22:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000089,0.0,0.000089,0.000092,0.000000,0.000888,0.048107,0.000000,1.0,0.000000
23,23,2010-01-01 23:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000081,0.0,0.000081,0.000076,0.000000,0.000808,0.048107,0.000000,1.0,0.000000
24,24,2010-01-02 00:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000073,0.0,0.000073,0.000059,0.000000,0.000735,0.048107,0.000000,1.0,0.000000

,Time,RAIN_RATE,GIUH_RUNOFF,INFILTRATION_EXCESS,DIRECT_RUNOFF,NASH_LATERAL_RUNOFF,DEEP_GW_TO_CHANNEL_FLUX,SOIL_TO_GW_FLUX,Q_OUT,POTENTIAL_ET,ACTUAL_ET,GW_STORAGE,SOIL_STORAGE,SOIL_STORAGE_CHANGE,SURF_RUNOFF_SCHEME,NWM_PONDED_DEPTH
Time Step,,,,,,,,,,,,,,,,
0,2010-01-01 00:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000809,0.0,0.000809,0.000179,0.000000,0.007533,0.045028,0.000000,1.0,0.000000
1,2010-01-01 01:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000725,0.0,0.000725,0.000133,0.000000,0.006807,0.045028,0.000000,1.0,0.000000
2,2010-01-01 02:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000651,0.0,0.000651,0.000103,0.000000,0.006156,0.045028,0.000000,1.0,0.000000
3,2010-01-01 03:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000585,0.0,0.000585,0.000088,0.000000,0.005571,0.045028,0.000000,1.0,0.000000
4,2010-01-01 04:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000527,0.0,0.000527,0.000078,0.000000,0.005044,0.045028,0.000000,1.0,0.000000
5,2010-01-01 05:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000475,0.0,0.000475,0.000071,0.000000,0.004570,0.045028,0.000000,1.0,0.000000
6,2010-01-01 06:00:00,0.000058,0.000000,0.000000,0.000000,0.0,0.000428,0.0,0.000428,0.000064,0.000058,0.004141,0.045028,0.000000,1.0,0.000000
7,2010-01-01 07:00:00,0.001453,0.000011,0.000019,0.000011,0.0,0.000387,0.0,0.000397,0.000057,0.000057,0.003755,0.046405,0.001376,1.0,0.000009
8,2010-01-01 08:00:00,0.000194,0.000005,0.000000,0.000005,0.0,0.000349,0.0,0.000354,0.000055,0.000055,0.003406,0.046544,0.000139,1.0,0.000004
9,2010-01-01 09:00:00,0.001020,0.000009,0.000009,0.000009,0.0,0.000316,0.0,0.000325,0.000053,0.000053,0.003090,0.047502,0.000958,1.0,0.000004
10,2010-01-01 10:00:00,0.000199,0.000003,0.000000,0.000003,0.0,0.000286,0.0,0.000288,0.000056,0.000056,0.002804,0.047644,0.000142,1.0,0.000002
11,2010-01-01 11:00:00,0.000393,0.000003,0.000001,0.000003,0.0,0.000259,0.0,0.000261,0.000060,0.000060,0.002546,0.047976,0.000332,1.0,0.000001
12,2010-01-01 12:00:00,0.000192,0.000000,0.000000,0.000000,0.0,0.000234,0.0,0.000235,0.000061,0.000061,0.002311,0.048107,0.000131,1.0,0.000000
13,2010-01-01 13:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000212,0.0,0.000212,0.000065,0.000000,0.002099,0.048107,0.000000,1.0,0.000000
14,2010-01-01 14:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000192,0.0,0.000192,0.000083,0.000000,0.001907,0.048107,0.000000,1.0,0.000000
15,2010-01-01 15:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000174,0.0,0.000174,0.000108,0.000000,0.001732,0.048107,0.000000,1.0,0.000000
16,2010-01-01 16:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000158,0.0,0.000158,0.000132,0.000000,0.001574,0.048107,0.000000,1.0,0.000000
17,2010-01-01 17:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000144,0.0,0.000144,0.000156,0.000000,0.001431,0.048107,0.000000,1.0,0.000000
18,2010-01-01 18:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000130,0.0,0.000130,0.000172,0.000000,0.001300,0.048107,0.000000,1.0,0.000000
19,2010-01-01 19:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000118,0.0,0.000118,0.000172,0.000000,0.001182,0.048107,0.000000,1.0,0.000000
20,2010-01-01 20:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000107,0.0,0.000107,0.000166,0.000000,0.001075,0.048107,0.000000,1.0,0.000000
21,2010-01-01 21:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000098,0.0,0.000098,0.000132,0.000000,0.000977,0.048107,0.000000,1.0,0.000000
22,2010-01-01 22:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000089,0.0,0.000089,0.000092,0.000000,0.000888,0.048107,0.000000,1.0,0.000000
23,2010-01-01 23:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000081,0.0,0.000081,0.000076,0.000000,0.000808,0.048107,0.000000,1.0,0.000000
24,2010-01-02 00:00:00,0.000000,0.000000,0.000000,0.000000,0.0,0.000073,0.0,0.000073,0.000059,0.000000,0.000735,0.048107,0.000000,1.0,0.000000

In [39]:
# df_cat = pd.read_csv('/home/exouser/Documents/cat-485547/outputs/ngen/cat-485547.csv')
final_timestamp = pd.read_csv('/home/exouser/Documents/cat-485547/outputs/ngen/cat-485547.csv', header=None, index_col=[0]).tail(1).iloc[0,0]
final_timestamp = datetime.strptime(final_timestamp.strip(), "%Y-%m-%d %H:%M:%S")

In [40]:
final_timestamp

datetime.datetime(2010, 1, 2, 0, 0)

In [43]:
final_timestamp = pd.read_csv("/home/exouser/Documents/cat-485547/outputs/ngen/nex-485547_output.csv", header=None, index_col=[0]).tail(1).iloc[0,0]
final_timestamp = datetime.strptime(final_timestamp.strip(), "%Y-%m-%d %H:%M:%S")

In [44]:
final_timestamp

datetime.datetime(2010, 1, 2, 0, 0)

In [67]:
f = "/home/exouser/Documents/cat-485547/outputs/ngen/nex-485547_output.csv"
df_nex = pd.read_csv(f, names=['timestamp', 'qlat'], index_col=[0])
df_nex

               timestamp      qlat
0    2010-01-01 00:00:00  0.850540
1    2010-01-01 01:00:00  0.762370
2    2010-01-01 02:00:00  0.684423
3    2010-01-01 03:00:00  0.615306
4    2010-01-01 04:00:00  0.553855
5    2010-01-01 05:00:00  0.499092
6    2010-01-01 06:00:00  0.450267
7    2010-01-01 07:00:00  0.443571
8    2010-01-01 08:00:00  0.384354
9    2010-01-01 09:00:00  0.357648
10   2010-01-01 10:00:00  0.306184
11   2010-01-01 11:00:00  0.277785
12   2010-01-01 12:00:00  0.247207
13   2010-01-01 13:00:00  0.223751
14   2010-01-01 14:00:00  0.202361
15   2010-01-01 15:00:00  0.183435
16   2010-01-01 16:00:00  0.166400
17   2010-01-01 17:00:00  0.150994
18   2010-01-01 18:00:00  0.137051
19   2010-01-01 19:00:00  0.124428
20   2010-01-01 20:00:00  0.112992
21   2010-01-01 21:00:00  0.102629
22   2010-01-01 22:00:00  0.093233
23   2010-01-01 23:00:00  0.084712
24   2010-01-02 00:00:00  0.076982

In [83]:
df_nex['timestamp'] = pd.to_datetime(df_nex['timestamp']).dt.strftime('%Y%m%d%H%M')
df_nex = df_nex.set_index('timestamp')
df_nex = df_nex.T
df_nex.index = [int(os.path.basename(f).split('-')[1].split('_')[0])]
df_nex = df_nex.rename_axis(None, axis=1)
df_nex.index.name = 'feature_id'
df_nex

,201001010000,201001010100,201001010200,201001010300,201001010400,201001010500,201001010600,201001010700,201001010800,201001010900,...,201001011500,201001011600,201001011700,201001011800,201001011900,201001012000,201001012100,201001012200,201001012300,201001020000
feature_id,,,,,,,,,,,,,,,,,,,,,
485547,0.85054,0.76237,0.684423,0.615306,0.553855,0.499092,0.450267,0.443571,0.384354,0.357648,...,0.183435,0.1664,0.150994,0.137051,0.124428,0.112992,0.102629,0.093233,0.084712,0.076982

In [ ]:
f = "/home/exouser/Documents/cat-485547/outputs/ngen/cat-485547"
df_cat = pd.read_csv('/home/exouser/Documents/cat-485547/outputs/ngen/cat-485547.csv',usecols= ['Time', 'Q_OUT'])
df_cat.rename(columns={'Time': 'timestamp', 'Q_OUT': 'qlat'}, inplace=True)
df_cat['qlat']  = (df_cat['qlat'] * area * 1000000)/3600   # Convert from m3/s to L/s

# df_cat = df_cat.set_index('timestamp')
# df_cat = df_cat.T
# df_cat.index = [int(os.path.basename(f).split('-')[1].split('_')[0])]
# df_cat = df_cat.rename_axis(None, axis=1)
# df_cat.index.name = 'feature_id'
# df_cat

              timestamp      qlat
0   2010-01-01 00:00:00  0.000809
1   2010-01-01 01:00:00  0.000725
2   2010-01-01 02:00:00  0.000651
3   2010-01-01 03:00:00  0.000585
4   2010-01-01 04:00:00  0.000527
5   2010-01-01 05:00:00  0.000475
6   2010-01-01 06:00:00  0.000428
7   2010-01-01 07:00:00  0.000397
8   2010-01-01 08:00:00  0.000354
9   2010-01-01 09:00:00  0.000325
10  2010-01-01 10:00:00  0.000288
11  2010-01-01 11:00:00  0.000261
12  2010-01-01 12:00:00  0.000235
13  2010-01-01 13:00:00  0.000212
14  2010-01-01 14:00:00  0.000192
15  2010-01-01 15:00:00  0.000174
16  2010-01-01 16:00:00  0.000158
17  2010-01-01 17:00:00  0.000144
18  2010-01-01 18:00:00  0.000130
19  2010-01-01 19:00:00  0.000118
20  2010-01-01 20:00:00  0.000107
21  2010-01-01 21:00:00  0.000098
22  2010-01-01 22:00:00  0.000089
23  2010-01-01 23:00:00  0.000081
24  2010-01-02 00:00:00  0.000073

In [13]:
import os
x = int((os.path.basename("/home/exouser/Documents/cat-485547/outputs/ngen/nex-485548_output.csv").split('-')[1].split('_')[0]).split('.')[0])
x

485548

In [17]:
import xarray as xr
ds = xr.open_dataset('/home/exouser/Documents/cat-485547/outputs/troute/troute_output_201001010000.nc')

In [18]:
ds.sel({'feature_id': 485547})['flow'].values

array([0.17818804, 0.51905406, 0.63688016, 0.6339921 , 0.5928029 ,
       0.54315275, 0.49414667, 0.4647691 , 0.42715836, 0.39157766,
       0.35207874, 0.31626505, 0.28469482, 0.25731125, 0.23360085,
       0.21262771, 0.19362374, 0.17666501, 0.16123939, 0.14719519,
       0.13446413, 0.12312286, 0.11287827, 0.10351406], dtype=float32)